const menuoptions = [
    {
        name:"Genre",
        link:"#",
        dropdown:[
            {
                name:"Action",
                link:"#",
                genreID:"action"
            },
            {
                name:"Comedy",
                link:"#",
                genreID:"comedy"
            },
            {
                name:"Horror",
                link:"#",
                genreID:"horror"
            },
            {
                name:"Romance",
                link:"#",
                genreID:"romance"
            },
            {
                name:"Thriller",
                link:"#",
                genreID:"thriller"
            },
            {
                name:"Sci-Fi",
                link:"#",
                genreID:"scifi"
            },
            {
                name:"Drama",
                link:"#",
                genreID:"drama"
            },
            {
                name:"Mystery",
                link:"#",
                genreID:"mystery"
            },
            {
                name:"Crime",
                link:"#",
                genreID:"crime"
            },
            {
                name:"Animation",
                link:"#",
                genreID:"animation"
            },
            {
                name:"Adventure",
                link:"#",
                genreID:"adventure"
            },
            {
                name:"Fantasy",
                link:"#",
                genreID:"fantasy"
            },
            {
                name:"Family",
                link:"#",
                genreID:"family"
            },
            {
                name:"Biography",
                link:"#",
                genreID:"biography"
            },
            {
                name:"History",
                link:"#",
                genreID:"history"
            },
            {
                name:"War",
                link:"#",
                genreID:"war"
            },
            {
                name:"Documentary",
                link:"#",
                genreID:"documentary"
            },
            {
                name:"Music",
                link:"#",
                genreID:"music"
            },
            {
                name:"Sport",
                link:"#",
                genreID:"sport"
            },
            {
                name:"Western",
                link:"#",
                genreID:"western"
            },
            {
                name:"Short",
                link:"#",
                genreID:"short"
            },
            {
                name:"Film-Noir",
                link:"#",
                genreID:"filmnoir"
            },
            {
                name:"Talk-Show",
                link:"#",
                genreID:"talkshow"
            },
            {
                name:"News",
                link:"#",
                genreID:"news"
            }
        ]
    },
    {
        name:"Country",
        link:"#",
        dropdown:[
            {
                name:"India",
                link:"#",
                genreID:"india"
            },
            {
                name:"USA",
                link:"#",
                genreID:"usa"
            },
            {
                name:"UK",
                link:"#",
                genreID:"uk"
            },
            {
                name:"Australia",
                link:"#",
                genreID:"australia"
            },
            {
                name:"China",
                link:"#",
                genreID:"china"
            },
            {
                name:"France",
                link:"#",
                genreID:"france"
            },
            {
                name:"Germany",
                link:"#",
                genreID:"germany"
            },
            {
                name:"Italy",
                link:"#",
                genreID:"italy"
            },
            {
                name:"Japan",
                link:"#",
                genreID:"japan"
            },
            {
                name:"South Korea",
                link:"#",
                genreID:"southkorea"
            },
            {
                name:"Spain",
                link:"#",
                genreID:"spain"
            },
            {
                name:"Canada",
                link:"#",
                genreID:"canada"
            },
            {
                name:"Mexico",
                link:"#",
                genreID:"mexico"
            },
            {
                name:"Brazil",
                link:"#",
                genreID:"brazil"
            },
            {
                name:"Russia",
                link:"#",
                genreID:"russia"
            },
            {
                name:"Nigeria",
                link:"#",
                genreID:"nigeria"
            },
            {
                name:"Argentina",
                link:"#",
                genreID:"argentina"
            },
            {
                name:"Sweden",
                link:"#",
                genreID:"sweden"
            },
            {
                name:"Netherlands",
                link:"#",
                genreID:"netherlands"
            },
            {
                name:"Poland",
                link:"#",
                genreID:"poland"
            },
            {
                name:"Belgium",
                link:"#",
                genreID:"belgium"
            },
            {
                name:"Denmark",
                link:"#",
                genreID:"denmark"
            },
            {
                name:"Norway",
                link:"#",
                genreID:"norway"
            },
            {
                name:"Finland",
                link:"#",
                genreID:"finland"
            },
            {
                name:"Greece",
                link:"#",
                genreID:"greece"
            },
            {
                name:"Turkey",
                link:"#",
                genreID:"turkey"
            },
            {
                name:"Egypt",
                link:"#",
                genreID:"egypt"
            },
        ]
    },
    {
        name:"Movies",
        link:"#"
    },
    {
        name:"TV Shows",
        link:"#"
    },
    {
        name:"Top IMDB",
        link:"#"
    }, 
    {
        name:"Pricing",
        link:"/pricing"
    }
]

export default menuoptions;